apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: goweb
    image: ltaa/go-web
    volumeMounts:
      - mountPath: /data
        name: hp-pvc
  volumes:
  - name:  hp-pvc
    persistentVolumeClaim:
      claimName: storage-pvc
