apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /data
        name: hp-pvc
  volumes:
  - name:  hp-pvc
    persistentVolumeClaim:
      claimName: storage-pvc
