kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jane-rb
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
