kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carol-view
rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    verbs:
      - get
      - list
      - watch
    resources:
      - Pods
